spring.main.banner-mode = off
debug = false

# dfinition du message Hello
helloMessage = Hello, world
logfile = file.log

spring.datasource.url=jdbc:hsqldb:mem:myBase
spring.datasource.username=SA
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver

spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.hibernate.dialect = org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.show_sql = false
spring.jpa.hibernate.format_sql = false

server.port=8080

spring.main.allow-circular-references=true

# position des pages JSP (les vues)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.thymeleaf.enabled=false

# Configuration Mail FakeSMTP
spring.mail.host=localhost
spring.mail.port=10025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# DESACTIVER LE CHECK DE SANTE DU MAIL
management.health.mail.enabled=false
management.endpoint.health.show-details=never
management.endpoints.web.exposure.exclude=*
spring.mvc.pathmatch.matching-strategy=ant_path_matcher