spring.main.banner-mode = off
debug = false

# d�finition du message Hello
helloMessage = Hello, world
logfile = file.log


spring.datasource.url=jdbc:hsqldb:mem:myBase // Chaque test aura sa propre base virtuelle
spring.datasource.username=SA
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver

spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.hibernate.dialect = org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.show_sql = true
spring.jpa.hibernate.format_sql = true

// Le port sur lequel l'application va ecouter
server.port=8080

spring.main.allow-circular-references=true

# position des pages JSP (les vues)
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp

spring.thymeleaf.enabled=false
