
spring.main.banner-mode = off
debug = false

# définition du message Hello
helloMessage = Hello, world
logfile = file.log


spring.datasource.url=jdbc:hsqldb:mem:myBase // Chaque test aura sa propre base virtuelle
spring.datasource.username=SA
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver

spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.hibernate.dialect = org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.show_sql = true
spring.jpa.hibernate.format_sql = true

// Le port sur lequel l'application va écouter
server.port=8080


# position des pages JSP (les vues)
spring.mvc.view.prefix: /WEB-INF/jsp/
spring.mvc.view.suffix: .jsp

# un message
application.message: salut les copains

spring.main.allow-circular-references=true